### ISSUE TITLE
QuickTile fails pathologically when encountering panel reservations on edges between monitors

### ISSUE THREAD

**Issue by avaly** [ssokolow/quicktile#45] opened 2014-10-18 20:24 UTC
**Was:** Windows get resized to (0,0,0,0) on a clean install of Ubuntu 14.04.1

On a fresh install of Ubuntu 14.04.1 I get the following results when running quicktile on the latest `master` branch (commit 7571ac68b1dcab6c5f904497648815b4ebe1108a).

```
$ ./quicktile.py -d --debug
<class 'Xlib.protocol.request.QueryExtension'>
DEBUG: window: <wnck.Window object at 0x7ff418e7d5f0 (WnckWindow at 0x1955e00)>
DEBUG: Monitor: 0, gtk.gdk.Rectangle(0, 0, 1920, 1200)
DEBUG: dims [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
DEBUG: Result overlaps panel. Falling back to usableRect.
DEBUG: result (0, 0, 0, 0)
DEBUG: Monitor: 0, gtk.gdk.Rectangle(0, 0, 1920, 1200)
DEBUG: repositioning to (0, 0, 0, 0)
```

Earlier today, before performing the fresh install of Ubuntu 14.04.1, I was running Ubuntu 14.04.1 which was upgraded from a fresh install of Ubuntu 13.04. On that installation I was running a quicktile fork based on an old commit (7a5bf6ffb2a70d557a736f516f08d70ea5f9af83). Everything worked fine.

However, on the fresh install of 14.04.1, when running the old commit 7a5bf6ffb2a70d557a736f516f08d70ea5f9af83, I get the following debug output:

```
$ ./quicktile.py -d --debug
<class 'Xlib.protocol.request.QueryExtension'>
DEBUG: NET_WM_WINDOW_TYPE: ('ATOM', 32, ['_NET_WM_WINDOW_TYPE_NORMAL'])
DEBUG: win <gtk.gdk.Window object at 0x7f2b10078280 (GdkWindow at 0x27d1480)>
DEBUG: useArea []
DEBUG: useRect gtk.gdk.Rectangle(0, 0, 0, 0)
DEBUG: winGeom (49, 24, 200, 228)
DEBUG: monitorID 0
DEBUG: dims [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
DEBUG: Result overlaps panel. Falling back to usableRect.
DEBUG: result (0, 0, 0, 0)
```

Could it be that quicktile depeneds on some library that was available in Ubuntu 13.04, but is not present in 14.04?

Any suggestions to track down the issue and find a workaround would be appreciated!

**Comment by avaly** [comment] 2015-02-15 14:57
Any updates on this one?

**Comment by avaly** [comment] 2015-02-15 16:18
Weirdly enough, [removing the launcher bar from the second monitor](http://askubuntu.com/questions/107583/how-can-i-remove-duplicate-second-unity-launcher-on-a-dual-screen-setup) was enough to fix the issue I was experiencing.

However, I do think the code can still be improved to handle this edge cases.

**Comment by ssokolow** [comment] 2015-02-15 20:04
Sorry for dropping the ball. My schedule got messed up and I've been struggling to keep the TODO completion rate above the TODO arrival rate.

As for fixing it, that's not weird at all. The problem happens because, when QuickTile receives word that the panel on the second monitor has reserved space, it misinterprets that request as reserving the entire left monitor.

**Comment by ssokolow** [comment] 2020-01-24 10:24
Renaming this to the actual problem as part of cleaning up TODOs in preparation to fix them.

Sorry for going silent for so long.

**Comment by ssokolow** [comment] 2020-01-25 11:22
In case anyone's wondering about the root cause of this issue, it's that I was working from the [official spec](https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html#NETWMSTRUTPARTIAL) for `_NET_WM_STRUT_PARTIAL`, and it makes no mention of this use case in such a way as to imply that the correct behaviour is to treat an entire monitor as reserved.

**Comment by ssokolow** [comment] 2020-01-25 16:32
Since `UseWorkarea` has been removed in the GTK 3.x port, I'm setting this as a requirement for that release to remind myself to write a fix for this before I release it.

I may need to rethink my internal representation of panels so it remembers which edge of the desktop the panel was calculated against (ie. which dimension is length and which is thickness) but I'm imagining something along the lines of "if a panel's thickness covers the entire span of the monitor in question, ignore it."

**Comment by ssokolow** [comment] 2020-01-26 11:28
No fix yet, but I just converted the numbers from your `--debug` output into a unit test so I'll know once I *have* successfully fixed it.

**Comment by ssokolow** [comment] 2020-01-27 17:57
A fix that superficially seems to work is now in my local copy of QuickTile. I'll be pushing it to the `gtk3_port` branch as soon as I've written some unit tests to improve my confidence in its correctness.

**Comment by ssokolow** [comment] 2020-01-28 11:11
OK. The version with the fix is now in the `gtk3_port` branch. I don't have any panels on interior edges, but the code passes the unit test I built from your `--debug` output.

Please test and let me know if you encounter any problems.

**Closed** 2020-02-09 08:35 UTC
Labels: bug, confirmed, fix in dev branch, needs more info
