### ISSUE TITLE
Switching workspace doesn't trigger if no windows

### ISSUE THREAD

**Issue by anthillsocial** [ssokolow/quicktile#85] opened 2017-06-19 14:15 UTC
On LXQT a quickkey to scroll through available workspaces fails to trigger if no window is open on an individual workspace. i.e. an open window is required to trigger the action. 
Tom

**Comment by ssokolow** [comment] 2017-06-19 15:50
What is the specific command name you keybinding is set to trigger?

**Comment by anthillsocial** [comment] 2017-06-19 21:54
$ quicktile workspace-go-next
and
$ quicktile workspace-go-prev

**Comment by ssokolow** [comment] 2017-06-22 08:23
Thanks and sorry for taking so long. It's been a messy couple of days.

I'll try to look into it within the next couple of days.

**Comment by ssokolow** [comment] 2017-06-25 21:42
Sorry for the delay. Things have slowed down because I caught a summer cold.

I'll need to try to reproduce the problem once my brain is working again.

A quick look at the code doesn't present any obvious source of problems. The algorithm basically boils down to:

1. Ask libwnck to retrieve the active workspace. (Your window manager may refuse this request)
2. Ask libwnck to retrieve the workspace with the requested relationship to the current one (Your window manager may refuse this request)
3. Ask libwnck to activate (focus) the target workspace (Your window manager may refuse this request)

When I'm not so tired and fuzzed-out, I'll see if I can reproduce the problem to verify my suspicions that it's either a bug in libwnck or the WM refusing one of QuickTile's requests, rather than QuickTile being at fault.

**Comment by anthillsocial** [comment] 2017-07-10 10:22
No need to apologise - you are doing work for free!
I've also been away for a couple of weeks, thanks for the info, really useful to understand elements of the software structure.

**Comment by ssokolow** [comment] 2017-08-20 23:48
OK, I'm starting to get to resolving issues, but this will still take some time because the problem doesn't manifest under my KDE setup and I'm going to need to spend some time clearing hard drive space before I have room to set up a testing VM.

**Comment by ssokolow** [comment] 2017-08-23 13:24
I actually managed to trigger this and track it down today and I just pushed a fix.

I'd forgotten about a bit of code that assumed all commands need active windows. Thanks for reporting it.

**Closed** 2017-08-23 13:23 UTC
Labels: bug

**Comment by anthillsocial** [comment] 2017-08-23 14:12
That's brilliant - thank you for all your efforts, its really appreciated!
